apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      hostAliases:
      - ip: 127.0.1.1
        hostnames:
         - {{ .Values.name }}.localdomain
         - {{ .Values.name }}
      containers:
      - image: {{ .Values.name }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        resources: {}
        securityContext:
          privileged: true
      restartPolicy: Always
{{- if eq .Values.mode "local" }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                -  {{ .Values.node }}
{{- end }}
      serviceAccountName: ""
{{- if eq .Values.mode "node-name" }}
      nodeName: {{ .Values.node }}
{{- end }}
      serviceAccountName: ""
      volumes: null
status: {}


